<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="sketchbrahma-Latitude-3520" failures="1" tests="4" name="Default test" time="33.108" errors="0" timestamp="2025-01-31T18:49:36 IST">
  <testcase classname="com.wise.tests.EndtoEndCases" name="performLogin" time="4.358"/>
  <testcase classname="com.wise.tests.EndtoEndCases" name="classRoom" time="1.227"/>
  <testcase classname="com.wise.tests.EndtoEndCases" name="scheduleSession" time="22.927"/>
  <testcase classname="com.wise.tests.EndtoEndCases" name="assertSession" time="0.859">
    <failure type="java.lang.Exception" message="host Name expected [[[ChromeDriver: chrome on linux (88c9d3374f35469953718eb508df9f19)] -&amp;gt; css selector: .session .text-uppercase]] but found [HOSTED BY WISE TESTER]">
      <![CDATA[java.lang.Exception: host Name expected [[[ChromeDriver: chrome on linux (88c9d3374f35469953718eb508df9f19)] -> css selector: .session .text-uppercase]] but found [HOSTED BY WISE TESTER]
at com.wise.pagefactory.GroupCoursesPage.verifyTheHostName(GroupCoursesPage.java:158)
at com.wise.tests.EndtoEndCases.assertSession(EndtoEndCases.java:44)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- assertSession -->
</testsuite> <!-- Default test -->
